accounts/urls.py
from django.urls import path

from . import views

app_name = "accounts"

urlpatterns = [
    path('login/', views.login_user, name = 'login_user'),
    path('logout/', views.logout_user, name = 'logout_user'), 
    path('register/', views.register_user, name = 'register_user') 
]

apprendreDjango/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('manga/', include('mangalib.urls')),
    path('accounts/', include('accounts.urls'))
]

mangalib/urls.py
from django.urls import path
from . import views

app_name = "mangalib"

urlpatterns = [
    path('', views.index, name='index'), # manga/
    path('<int:book_id>/', views.show, name='show'), # manga/id
    path('ajouter-livre/', views.add, name ='add'),
    path('modifier-livre/<int:book_id>/', views.edit, name = "edit"),
    path('suppimer-livre/<int:book_id>/', views.remove, name='delete')
]

mangalib/models.py
from django.db import models

"""
    primary_key
    unique
    default
    null
    blank

    CharField
    IntegerField
    DateField
    DateTimeField
    FloatField
    EmailField
    BooleanField
    EmailField

    Many-To-Many : * -- * 
        field = models.ManyToManyField(ModelA)
    One-To-One : 1 -- 1
        
"""

class Author(models.Model):
    name = models.CharField(max_length=64, unique=True, verbose_name= "Nom")
    
    def __str__(self):
        return self.name
    
    class Meta:
        verbose_name = "Auteur"
        verbose_name_plural = "Auteurs"
        #db_table = ""    #modifier le nom de la table enregistree dans la bd

class Book(models.Model):
    title = models.CharField(max_length=64, unique=True, verbose_name= "Titre")
    quantity = models.IntegerField(default = 1, verbose_name= "Quantité")
    author = models.ForeignKey(Author, on_delete=models.DO_NOTHING, verbose_name= "Auteur")
    
    def __str__(self): 
        return self.title
    
    class Meta:
        verbose_name = "Livre"
        verbose_name_plural = "Livres"
        permissions = [
            ('apply_promo_code', 'Peut appliquer des migrations')
        ]

mangalib/forms.py
from django import forms
from .models import Book, Author

"""
    CharField
"""

"""class SomeForm(forms.Form):
    username = forms.CharField(label= "Nom d'utilisateur",
                               max_length= 25, 
                               required = True)
    password = forms.CharField(label = "Mot de passe", widget=forms.PasswordInput)
    bio = forms.CharField(label = "Biographie", widget = forms.Textarea)
    publicate = forms.CharField(label = "Publier le contenu ?", widget=forms.CheckboxInput)
    
    languages = [('c', 'Langage C'), ('php', 'Langage PHP')]
    language = forms.MultipleChoiceField(label = "Langages connus", widget = forms.CheckboxSelectMultiple, choices = languages)
    
    colors = [('1', 'Bleu'), ('2', "Jaune"), ('3', 'Rouge'), ('4', 'Vert')]
    color = forms.ChoiceField(label = "Couleur dominante", choices = colors, widget = forms.RadioSelect)
    
    countries = [("1", 'Cameroun'), ("2", "Congo")]
    country = forms.ChoiceField(label = "Pays", choices = countries)"""
    
class BookForm(forms.ModelForm):
    author = forms.ModelChoiceField(queryset= Author.objects.all(), label="Auteur")
    
    class Meta:
        model = Book
        fields = ['title', 'author', 'quantity']
        labels = {'title': 'Titre', 'quantity': 'Quantité'}
        
    def clean_quantity(self):
        quantity = self.cleaned_data['quantity']
        
        if quantity <= 0 or quantity > 100:
            raise forms.ValidationError("La quantité du livre doit etre comprise entre 1 et 100")
        
        return quantity
    
    def clean(self):
        title = self.cleaned_data.get('title')
        quantity = self.cleaned_data.get('quantity')
        
        if title and quantity:
            if title.startswith('Dragon Ball') and quantity < 10:
                raise forms.ValidationError("Minimum une quantité de 10 pour un livre Dragon Ball")

        return self.cleaned_data

mangalib/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponse
from django.template import loader
# Create your views here.

import datetime
from .models import Book, Author
from .forms import BookForm
from django.contrib.auth.decorators import login_required, permission_required, user_passes_test

def is_visitor(user):
    return user.groups.filter(name = "Visiteur").exists()

"""
    SELECT * : all(), get()

    WHERE : filter() .filter(title = "Naruto")
                __gt, __lt,  gte, __lte, __startswith
    ORDER BY : order_by() -desc
    LIMIT : [:N]

    save(), delete()

    INSERT : create()

    Many-To-Many : * -- * 
         book.authors.add(author)
    
    raw() SQL
    
    
    user.has_perm()
        .all()
        .add()
        .remove()
        .clear()
        .set([])
        
    user.groups.set([gr1, gr2])
    user.groups.add()
    user.groups.remove()
    user.groups.clear()
    
    LoginRequiredMixin
    PermissionRequiredMixin
    
    Django Guardian
    Rules
"""

# settings.LOGNI_URL : /accounts/login

def index(request):
    # context = {"message": "Hello World !",
    #            "numberNews": 15,
    #            "usersList" : ['Tata', 'Toto', 'Titi'],
    #            "publication" : datetime.datetime.now(),
    #            "d1" : datetime.datetime.now(),
    #            "d2" : datetime.datetime.now(),
    #            "text" : "Bonjour et bienvenue sur la bibliotheque de mangas et animes"
    #            }
    context = {
        "books": Book.objects.all()
    }
    
    """if request.method == 'POST':
        form = SomeForm(request.POST)
        
        if form.is_valid():
            return redirect('mangalib:index')
    else:
        form = SomeForm()
    
    context = {"form": form}
    return render(request, "mangalib/index.html", context)"""
    

    return render(request,"mangalib/index.html", context)
    #template = loader.get_template("mangalib/index.html")
    #return HttpResponse(template.render(context, request))

#@login_required
#@permission_required('mangalib.view_book', raise_exception = True)
@user_passes_test(is_visitor)
def show(request, book_id):
    context = {"book": get_object_or_404(Book, pk = book_id)}
    return render(request, "mangalib/show.html", context)    


@permission_required('mangalib.add_book', raise_exception = True)
def add(request):
    if request.method == 'POST':
        form = BookForm(request.POST)
        
        if form.is_valid():
            form.save()
            return redirect("mangalib:index")
    else:
        form = BookForm()
        
    return render(request,"mangalib/book-form.html", {"form": form})
    
    #author = Author.objects.get(name = "Akira Toriyama")
    
    #book = Book.objects.create(title = "Dragon Ball Z", quantity = 13, author = author)
    
    #book = Book(title = "Dragon Ball Z", quantity = 13, author = author)
    #book.save()

    #return redirect("mangalib:index")

@permission_required('mangalib.change_book', raise_exception = True)
def edit(request, book_id):
    book =  Book.objects.get(pk = book_id)
    
    if request.method == 'POST':
        form = BookForm(request.POST, instance = book)
        
        if form.is_valid():
            form.save()
            return redirect("mangalib:index")
    else:
        form = BookForm(instance = book)
        
    return render(request,"mangalib/book-form.html", {"form": form})    
    #book =  Book.objects.get(title = "Naruto")
    #book.title = "Naruto Shippuden"
    #book.save()

    #return redirect("mangalib:index")

@permission_required('mangalib.delete_book', raise_exception = True)
def remove(request, book_id):
    #book =  Book.objects.filter(title__startswith = "Dragon Ball")
    book =  Book.objects.get(pk = book_id)
    book.delete()

    return redirect("mangalib:index")
 

mangalib/templates/mangalib/book-form.html
{% load static %}
{% load customtags %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Mes Mangas</title>
    <link rel="stylesheet" href="{% static 'global.css' %}">
    <link rel="stylesheet" href="{% static 'mangalib/css/style.css' %}">
</head>
<body>
    <h1 style="color: #6992e9;">Gestion de livre</h1>

    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="ENVOYER">
    </form>
    
</body>
</html>

mangalib/templates/mangalib/home.html
{% load static %}
{% load customtags %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Mes Mangas</title>
    <link rel="stylesheet" href="{% static 'global.css' %}">
    <link rel="stylesheet" href="{% static 'mangalib/css/style.css' %}">
</head>
<body>
    <h1 style="color: #6992e9;">Bienvenue sur MangaLib !</h1>
    <p>{{ message | upper }}</p>
    <p>Nous sommes le {{ publication|date:"d/m/Y" }}</p>
    <p>{{ d1|timesince:d2 }}</p>
    <p>{{ text|truncatewords:2 }}</p>
    <p>{{ numberNews }} actualité{{ numberNews|pluralize }}</p>
    <p>{{ message|first_char }}</p>
    <p>{{ message|lengthis:5 }}</p>
    <p>{% hello_world nelson %}</p>
    {% comment "Ce paragraphe ne doit pas etre affiche" %}
        <p>Bonjour !</p>
        {% debug %}
    {% endcomment %}

    {% lorem 5 w %}

    {% now "l F d-m-Y H:i:s" %}
    <h2>Contenu d'un autre fichier</h2>
    {% include "mangalib/other.html" %}

    <p>Rendez-vous sur <a href="{% url 'index' %}">MangaLib</a></p>
    
    {% if numberNews > 0 %}
        <p>Des news sont disponibles !</p>
    {% else %}
        <p>Pas de news...</p>
    {% endif %}

    <h2>Liste des Users : </h2>
    
    {% for user in usersList %}
        <p>{{ user }}</p>
    {% empty %}
        <p>Pas d'utilisateurs...</p>
    {% endfor %} 

     

</body>
</html>

mangalib/templates/mangalib/index.html
{% load static %}
{% load customtags %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Mes Mangas</title>
    <link rel="stylesheet" href="{% static 'global.css' %}">
    <link rel="stylesheet" href="{% static 'mangalib/css/style.css' %}">
</head>
<body>
    {% if perms.mangalib.delete_book %}
        <p>Oui, c'est bon</p>
    {% endif %}

    {% if user.is_authenticated %}
        <p>Connecté sous {{ user.username }} | <a href="{% url 'accounts:logout_user' %}">Déconnexion</a></p>
    {% else %}
        <p><a href="{% url 'accounts:login_user' %}">Connexion</a> | <a href="{% url 'accounts:register_user' %}">Inscription</a></p>
    {% endif %}

    <h1>Bienvenue sur MangaLib !</h1>
    <p><a href="{% url 'mangalib:add' %}">[+]Ajouter</a> | 
    </p>
    <table>
        <thead>
            <tr>
                <td>Nom</td>
                <td>Auteur</td>
                <td>QTE</td>
                <td colspan="2">ACTIONS</td>
            </tr>
        </thead>
        <tbody>
            {% for book in books %}
                <tr>
                    <td><a href="{% url 'mangalib:show' book.id %}" style="color:rgb(140, 180, 241)">{{ book.title }}</a></td>
                    <td>{{ book.author.name }}</td>
                    <td>{{ book.quantity }}</td>
                    <td>
                        <a href="{% url 'mangalib:edit' book.id %}" class="edit">[e]Modifier</a>
                    </td>
                    <td>
                        <a href="{% url 'mangalib:delete' book.id %}" class="delete">[-]Supprimer</a>
                    </td>
                </tr>
            {% empty %}
                <p>Pas de mangas..</p>
            {% endfor %}
        </tbody>
    </table>
    

    <!-- <form method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="ENVOYER">
    </form> -->
</body>
</html>

mangalib/templates/mangalib/other.html
<ul>
    <li>Lundi</li>
    <li>Mardi</li>
    <li>{% lorem 10 w %}</li>
</ul>

mangalib/templates/mangalib/show.html
{% load static %}
{% load customtags %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Mes Mangas | {{ book.title }}</title>
    <link rel="stylesheet" href="{% static 'global.css' %}">
    <link rel="stylesheet" href="{% static 'mangalib/css/style.css' %}">
</head>
<body>
    <h1 style="color: #6992e9;">{{ book.title }}</h1>
    <p>Quantité : {{ book.quantity }}</p>
    <p>Auteur : {{ book.author.name }}</p>
    <p><a href="{% url 'mangalib:index' %}">&laquo; Revenir à la liste des livres</a></p>

</body>
</html>